- name: create virtualenv
  command: virtualenv {{ virtualenv_dir }} --python=python3
  args:
    creates: "{{ virtualenv_dir }}/bin/pip"

- name: install requirements.txt in virtualenv
  pip:
    requirements={{ source_dir }}/requirements.txt
    executable={{ virtualenv_dir }}/bin/pip