- name: fetch latest source
  git: repo=https://github.com/rebeckag/openid-course_teaching-material dest={{ provider_dir }} version=361546d force=yes

- include: ../../../tasks/virtualenv.yml
  vars:
    virtualenv_dir: "{{ provider_virtualenv_dir }}"
    source_dir: "{{ provider_source_dir }}"

- name: create config.yaml
  template: src=config.yaml.j2
            dest="{{ provider_source_dir }}/config.yaml"
  notify:
    - restart provider

- name: create Upstart script
  template: src=provider-gunicorn-upstart.conf.j2
            dest=/etc/init/{{ provider_service }}.conf
  notify:
    - restart provider
